services:
  # floci is a replacement for localstack. It emulates AWS resources (sqs, sns, s3 etc) for local development
  # See: https://floci.io for more details
  floci:
    image: hectorvent/floci:latest-aws
    ports:
      - '4566:4566'
    env_file:
      - 'compose/aws.env'
    environment:
      FLOCI_DEFAULT_REGION: eu-west-2
    volumes:
      - ./compose/floci/start.d:/etc/floci/init/start.d:ro
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - '6379:6379'
    networks:
      - cdp-tenant

  oracledb:
    image: container-registry.oracle.com/database/free:23.8.0.0
    ports:
      - '1521:1521'
    environment:
      ORACLE_PWD: password
    volumes:
      - oracledb-data:/opt/oracle/oradata
    healthcheck:
      test: ['CMD', '/opt/oracle/checkDBStatus.sh']
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:7.0.28
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    volumes:
      - ./compose/mongo:/docker-entrypoint-initdb.d:ro
      - mongodb-data:/data
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.hello().ok']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mongodb-data:
  oracledb-data:

networks:
  cdp-tenant:
    driver: bridge
    name: cdp-tenant
