-- ─────────────────────────────────────────────────────────────────────────────
-- Add UPDATED_DATETIME columns to tables for change detection POC
-- ─────────────────────────────────────────────────────────────────────────────

ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = AHBRP;

-- Add UPDATED_DATETIME to PARTY table
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE party ADD (UPDATED_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Add UPDATED_DATETIME to PARTY_STATE table
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE party_state ADD (UPDATED_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Add UPDATED_DATETIME to PERSON table
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE person ADD (UPDATED_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Add UPDATED_DATETIME to ORGANISATION table
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE organisation ADD (UPDATED_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Add UPDATED_DATETIME to LOCATION table
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE location ADD (UPDATED_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Add UPDATED_DATETIME to FEATURE_STATE table
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE feature_state ADD (UPDATED_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Add UPDATED_DATETIME to ADDRESS table
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE address ADD (UPDATED_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Add UPDATED_DATETIME to BS7666_ADDRESS table
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE bs7666_address ADD (UPDATED_DATETIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Create indexes on UPDATED_DATETIME for efficient polling
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_party_updated ON party (UPDATED_DATETIME)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_party_state_updated ON party_state (UPDATED_DATETIME)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_person_updated ON person (UPDATED_DATETIME)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_organisation_updated ON organisation (UPDATED_DATETIME)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_location_updated ON location (UPDATED_DATETIME)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_feature_state_updated ON feature_state (UPDATED_DATETIME)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_address_updated ON address (UPDATED_DATETIME)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'CREATE INDEX idx_bs7666_address_updated ON bs7666_address (UPDATED_DATETIME)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Update existing rows to have recent timestamps (for POC testing)
UPDATE party SET UPDATED_DATETIME = SYSTIMESTAMP - INTERVAL '5' MINUTE WHERE party_pk IN (61001, 61002, 61003);
UPDATE party_state SET UPDATED_DATETIME = SYSTIMESTAMP - INTERVAL '5' MINUTE WHERE party_pk IN (61001, 61002, 61003);
UPDATE person SET UPDATED_DATETIME = SYSTIMESTAMP - INTERVAL '5' MINUTE WHERE party_pk IN (61001, 61002);
UPDATE organisation SET UPDATED_DATETIME = SYSTIMESTAMP - INTERVAL '5' MINUTE WHERE party_pk = 61003;

COMMIT;
