-- Seed data for PARTY table (for change detection tests)

INSERT INTO PARTY (PARTY_PK, PARTY_ID, UPDATED_DATETIME)
VALUES (61001, 'P000001', SYSTIMESTAMP - INTERVAL '1' HOUR);

INSERT INTO PARTY (PARTY_PK, PARTY_ID, UPDATED_DATETIME)
VALUES (61002, 'P000002', SYSTIMESTAMP - INTERVAL '1' HOUR);

INSERT INTO PARTY (PARTY_PK, PARTY_ID, UPDATED_DATETIME)
VALUES (61003, 'P000003', SYSTIMESTAMP - INTERVAL '1' HOUR);

-- Insert corresponding PARTY_STATE records
INSERT INTO PARTY_STATE (PARTY_PK, PARTY_STATUS_CODE, PARTY_STATE_TO_DTTM, UPDATED_DATETIME)
VALUES (61001, 'ACTIVE', NULL, SYSTIMESTAMP - INTERVAL '1' HOUR);

INSERT INTO PARTY_STATE (PARTY_PK, PARTY_STATUS_CODE, PARTY_STATE_TO_DTTM, UPDATED_DATETIME)
VALUES (61002, 'ACTIVE', NULL, SYSTIMESTAMP - INTERVAL '1' HOUR);

INSERT INTO PARTY_STATE (PARTY_PK, PARTY_STATUS_CODE, PARTY_STATE_TO_DTTM, UPDATED_DATETIME)
VALUES (61003, 'ACTIVE', NULL, SYSTIMESTAMP - INTERVAL '1' HOUR);

COMMIT;
