-- Create placeholder tables for PayloadCalculator.js compatibility
-- These tables exist in production SAM but are empty in Docker test environment

CREATE TABLE PARTY_VERSION (
  PARTY_PK NUMBER(12) NOT NULL,
  PARTY_TYPE VARCHAR2(20),
  PARTY_VERSION_TO_DATETIME DATE,
  UPDATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

CREATE TABLE PERSON (
  PARTY_PK NUMBER(12) NOT NULL PRIMARY KEY,
  PERSON_GIVEN_NAME VARCHAR2(50),
  PERSON_FAMILY_NAME VARCHAR2(50),
  PERSON_BIRTH_DATE DATE,
  UPDATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

CREATE TABLE ORGANISATION (
  PARTY_PK NUMBER(12) NOT NULL PRIMARY KEY,
  ORGANISATION_NAME VARCHAR2(200),
  ORGANISATION_TYPE_CODE VARCHAR2(20),
  UPDATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

CREATE TABLE PARTY_CONTACT_ADDRESS (
  PARTY_CONTACT_ADDRESS_PK NUMBER(12) NOT NULL PRIMARY KEY,
  PARTY_PK NUMBER(12) NOT NULL,
  ADDRESS_PK NUMBER(12),
  TELECOM_ADDRESS_PK NUMBER(12),
  PARTY_CONTACT_TO_DATE DATE,
  UPDATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

CREATE TABLE BS7666_ADDRESS (
  ADDRESS_PK NUMBER(12) NOT NULL PRIMARY KEY,
  PAON_START_NUMBER VARCHAR2(10),
  PAON_DESCRIPTION VARCHAR2(100),
  STREET VARCHAR2(100),
  TOWN VARCHAR2(50),
  ADMINISTRATIVE_AREA VARCHAR2(50),
  POSTCODE VARCHAR2(10),
  UPDATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

CREATE TABLE TELECOM_ADDRESS (
  TELECOM_ADDRESS_PK NUMBER(12) NOT NULL PRIMARY KEY,
  TELECOM_ADDRESS_TYPE VARCHAR2(20),
  MOBILE_NUMBER VARCHAR2(20),
  TELEPHONE_NUMBER VARCHAR2(20),
  INTERNET_EMAIL_ADDRESS VARCHAR2(100),
  UPDATED_DATETIME TIMESTAMP(6) DEFAULT SYSTIMESTAMP
);

COMMIT;
