name: Publish Hot Fix

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    name: CDP-build-hotfix-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          fetch-depth: 0 # Depth 0 is required for branch-based versioning

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Login to oracle container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: container-registry.oracle.com
          username: ${{ secrets.ORACLE_USERNAME }}
          password: ${{ secrets.ORACLE_SECRET_KEY }}

      - name: Install Oracle Instant Client
        id: oracle
        run: ./.github/scripts/oracle-instant-client.sh

      - name: Start only oracledb compose service
        run: npm run compose:up -- --wait --no-deps oracledb

      # Ensure tests pass. Add more checks if required
      - run: npm ci
      - run: npm test
        env:
          ORACLE_CLIENT_LIB_DIR: ${{ steps.oracle.outputs.install-path }}

      - name: Publish Hot Fix
        uses: DEFRA/cdp-build-action/build-hotfix@550c4792fac07cfd59eaea469bc0a17ce202cced # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

#     - run: npm install && npm test
#     - name: SonarCloud Scan
#       uses: SonarSource/sonarqube-scan-action@v5.3.1 #  (or check latest version on https://github.com/marketplace/actions/official-sonarqube-scan)
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
